version: "3.7"

services:
  app:
    container_name: "mondu-coding-challenge"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3001:3001
    volumes:
      - ./:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    env_file:
      - app.env
    depends_on:
      - db

  db:
    build: ./Db


